spring:
    h2:
        console:
            enabled: true
            path: "/h2"


    liquibase:
        enabled: true
        driver-class-name: com.mysql.cj.jdbc.Driver
        change-log: "classpath:db/db.changelog-1.0.0.yaml"
        url: "jdbc:mysql://${adapters.r2dbc.host}:${adapters.r2dbc.port}/${adapters.r2dbc.database}?useUnicode=true&allowPublicKeyRetrieval=true&useSSL=false"
        user: "${adapters.r2dbc.username}"
        password: "${adapters.r2dbc.password}"

springdoc:
    api-docs:
        enabled: true
        path: /v3/api-docs
    swagger-ui:
        enabled: true
        path: /swagger-ui.html
    webflux:
        use-root-path: true

adapters:
    r2dbc:
        host: "localhost"
        port: 3306
        database: "crediya_solicitudes"
        username: "root"
        password: "root"

microservices:
    usuarios:
        base-url: "http://localhost:8080"

webclient:
    timeout:
        connect: 5000
        response: 10000

cors:
    allowed-origins: "http://localhost:8080"